import { readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { attachmentsDir } from "@/lib/attachments";
import { getAttachment, getDb } from "@/lib/db";
import { handle, problem, requireUser, routeId } from "../../helpers";

/*
  Authorise, then stream. The directory is never served statically, because
  that would hand out every attachment to anyone who can guess a name.

  basename() on the stored path is belt and braces: the name was generated by
  lib/attachments.ts and cannot contain a separator, but this row could have
  come from a TestRail import one day and the cost of being sure is one call.
*/
export async function GET(_request: Request, context: { params: Promise<{ id: string }> }) {
  return handle(async () => {
    await requireUser();
    const attachment = getAttachment(getDb(), routeId((await context.params).id));
    if (!attachment) return problem(404, "No such attachment");

    const bytes = await readFile(join(attachmentsDir(), basename(attachment.storage_path)));
    return new Response(new Uint8Array(bytes), {
      headers: {
        "content-type": attachment.mime ?? "application/octet-stream",
        // Always an attachment, never inline: an uploaded SVG or HTML file
        // rendered in this origin would run script against a live session.
        "content-disposition": `attachment; filename="${attachment.filename.replace(/[^\w.\- ]/g, "_")}"`,
        "content-length": String(attachment.size ?? bytes.byteLength),
        "x-content-type-options": "nosniff",
      },
    });
  });
}
